name: 'CodeFreeze by Reviewer Count'
description: 'Changes reviewer counts with special PR blocking merges'
author: ''

# Define your inputs here.
inputs:
  token:
    description: 'Github token'
    required: true
  branch:
    description: 'Branch to be applied'
    required: true

# Define your outputs here.
outputs:
  debug:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
